- hosts: all
  tasks:
    - dnf:
        name: httpd
        state: present
    - copy:
        content: "Hello welcome"
        dest: /www/html/index.html

    - service:
        name: httpd
        state: started
